### ISSUE TITLE
Revise REAC score program for new HUD format

### ISSUE THREAD

**Issue by ptatian** [NeighborhoodInfoDC/HUD#116]
HUD has changed the format for the [downloadable REAC score file](https://www.hud.gov/program_offices/housing/mfh/rems/remsinspecscores/remsphysinspscores). We need to update our programs and [instructions](https://urbanorg.app.box.com/notes/317431397297) to accommodate this new format. 

I have already downloaded the latest file and saved to **L:\Libraries\HUD\Raw\REAC\02-06-2019**. 

So that programming for the older format does not break, macro program should check the file date and apply the new formatting only for files with update dates of 2/6/19 or later. 

Other changes may be needed to reconcile the two file formats.

**Comment by ptatian** [comment]
@mcohenui Would you be able to work on this issue? I can send you a charge code if you have time to work on it. Thanks.

**Comment by mcohenui** [comment]
@ptatian Sure thing. I am currently reviewing some final deliverables. But I could work on it Monday.

**Comment by ptatian** [comment]
@mcohenui Great. Thank you.

**Comment by mcohenui** [comment]
L:\Libraries\HUD\Prog\REAC\REAC_2019_02.log
