### ISSUE TITLE
Read-in CHAS data

### ISSUE THREAD

**Issue by rpitingolo** [NeighborhoodInfoDC/HUD#144]
Read in, format and label National CHAS data. 

@lhendey the program will read-in states, counties, places and tracts. Do you think it's worth doing the other geographies (counties split by place, consolidated cities, minor civil divisions, county/mcd/place remainders)? 

I will create a separate issue to save DC-specific summary files to the warehouse.

**Comment by lhendey** [comment]
@rpitingolo if they are the same format, it seems worth reading in all 3 geographies. (Also thinking about making use of these for DC area...)

**Comment by rpitingolo** [comment]
@lhendey as far as I can tell they are the same format. If I bump into any issues once I read in the other geographies I'll let you know.

**Comment by rpitingolo** [comment]
@lhendey also, is your intention to read-in all of the years of data (2012-16, 2011-15, etc.) as far back as it goes?

**Comment by lhendey** [comment]
@rpitingolo no. i think just something earlier - like 2006-10 and the most recent.

**Comment by rpitingolo** [comment]
@lhendey got it. thanks.

**Comment by rpitingolo** [comment]
L:\Libraries\HUD\Prog\CHAS\Read_CHAS_2012_16.log
L:\Libraries\HUD\Prog\CHAS\Read_CHAS_2006_10.log
