### ISSUE TITLE
Add MOE to CHAS summary data

### ISSUE THREAD

**Issue by rpitingolo** [NeighborhoodInfoDC/HUD#163]

**Comment by lhendey** [comment]
@rpitingolo can you do clean up on the issues from the ABQ project?

**Comment by rpitingolo** [comment]
@lhendey sure. Is the project # still active?

**Comment by lhendey** [comment]
@rpitingolo yes. had at least 4 hours for you. let me know if you need more

**Comment by rpitingolo** [comment]
@lhendey got it. Thanks.

**Comment by lhendey** [comment]
@rpitingolo can you complete this week? we need to wrap the project up so accounting can submit the final bill.

**Comment by rpitingolo** [comment]
L:\Libraries\HUD\Prog\CHAS\Output_ABQ_CHAS_Tables.log
