### ISSUE TITLE
Create LIHTC data sets for projects placed in service through 2020

### ISSUE THREAD

**Issue by ptatian** [NeighborhoodInfoDC/HUD#212]
- [x] In GitHub app, switch to HUD repo and fetch and pull any changes from remote. 

- [x] Create new _update-#nnn_ branch (with _nnn_ replaced by issue number) in HUD repo. 

- [x] Download latest HUD LIHTC database (ZIP file) from https://www.huduser.gov/portal/datasets/lihtc/property.html#data and save to `\\sas1\DCdata\Libraries\HUD\Raw\LIHTC\2020` folder. 

- [x] Extract CSV file from ZIP file and save in same folder. 

- [x] Copy template program `C:\DCData\Libraries\HUD\Prog\Templates\LIHTC_yyyy.sas` to `C:\DCData\Libraries\HUD\Prog`. Rename program file to LIHTC_2020.sas

- [x] Edit program file
- Replace yyyy with 2020
- Enter author name, date program created, and GitHub issue number in program header.
- Enter date of CSV file (from Windows Explorer) after the `filedate=` parameter in the macro. Date should be in SAS date format (e.g., `'01jan2021'd`).

- [x] Save and submit program. Review LOG and output for any warnings or errors.

- [x] Create a pull request and ask for a review (@-mention reviewer). 

- [x] After receiving approved review, merge branch, sync changes and batch submit program on `\\sas1` server. 

- [ ] Review LOG and output files for any warnings or errors. Check with reviewer if any problems.

- [ ] If program ran successfully, copy location of LOG file for `\\sas1` batch submit to comments in this issue and close issue.

**Comment by dharvey17** [comment]
LOG file location: \\sas1\DCDATA\Libraries\HUD\Prog\LIHTC\LIHTC_2020
